.Dd September 17, 2020
.Dt HTCOMPACT 1
.Os \" Current operating system.
.
.Sh NAME
.Nm htcompact
.Nd summarize and analyse HTCondor job log files
.
.Sh SYNOPSIS
.Nm
.Op Ar
.Op Fl afhrsv
.Op Fl Fl help
.Op Fl Fl files
.Op Fl m Ar mode
.Op Fl Fl mode Ar mode
.Op Fl Fl version
.Op Fl Fl verbose
.Op Fl Fl std-log Ar suffix
.Op Fl Fl std-out Ar suffix
.Op Fl Fl std-err Ar suffix
.Op Fl Fl ignore Ar keywords
.Op Fl Fl show-more Ar keywords
.Op Fl c Ar config
.Op Fl Fl config Ar config
.Op Fl Fl no-config
.Op Fl Fl recursive
.Op Fl Fl generate-log-file
.Op Fl Fl filter Ar keywords Op Fl Fl extend
.Op Fl Fl reverse-dns-lookup
.Op Fl Fl tolerated-usage Ar threshold
.Op Fl Fl bad-usage Ar threshold
.
.Sh DESCRIPTION
The
.Nm
script takes files and directories as input with given flags and prints out a
readable result of valid HTCondor log files.
There are 4 main modes to work with this facility.
The default and analyser mode are mostly made for single log analytics.
The summariser and analysed-summary mode,
are made to summarise huge collections of log files,
to give a view on the average used resources and occurred errors.
More details about the different modes below.
.Pp
Its arguments are as follows:
.Bl -tag -width Ds
.
.It Ar FILES | Fl f Ar FILES | Fl Fl files Ar FILES
just pass any log files or directories,
you just need to separate them by space.
There is no need to use the flags,
but sometimes you have to use them,
to escape the previous option, for ex:
.Bd -literal
    htcompact --ignore all-resources --files log1 log2

to prevent this, always hand the files first, like:

    htcompact log1 log2 --ignore all-resources
.Ed
.
.It Ar OPTIONS
.
.It Fl h | Fl Fl help
Prints a summary of
.Nm Ap s
command\[hy]line options and exits.
.
.It Fl m Ar mode | Fl Fl mode Ar mode
Specify the mode, to interpret HTCondor log files,
.Bd -literal
Valid arguments:
 ['a' or 'analyse', 's' or 'summarize',
 'as' or 'analysed-summary', 'd' or 'default']
.Ed
.Bd -literal
the standard mode of the script is 'default'

default mode:
    This mode just provides a really basic overview,
    about how the output can look like
    and what information is gathered.

analyse mode:
    For more detailed output, use the analyser mode.
    Features:
    - provides ram histogram
    - shows HTCondor errors
    - more details in general
    - have a look in running processes

summarize mode:
    summarise a collection of log files based on its used resources
    Features:
    - average usages of all collected log files
    - average usage and durations on each host node
    NOTE: this will ignore running, aborted and other processes,
          that do not contain details about the resource usages

analysed-summary mode:
    This mode is a combination of the summariser and analyser mode.
    Features:
    - Seperate the summation based on the termination types
    - Also handles running processes

.Ed
.
.It Fl s
Short for
.Fl Fl mode Ar summarize .
When used with
.Fl a ,
it's the same as
.Fl Fl mode Ar analysed-summary
.
.It Fl a
Short for
.Fl Fl mode Ar analyse .
When used with
.Fl s ,
it's the same as
.Fl Fl mode Ar analysed-summary
.
.It Fl Fl filter Ar keywords Op OPTIONS
Its options are as follows:
.Bl -tag -width Ds
.It Ar OPTIONS
.Op Fl m Ar mode | Fl Fl mode Ar mode
.Op Fl Fl extend
.
.It Fl m Ar mode | Fl Fl mode Ar mode
Forward the results, to be processed.
.It Fl Fl extend
will include these keywords:
.Bd -literal
["err", "error", "warn", "warning", "exception",
 "aborted", "abortion", "abnormal", "fatal"]
.Ed
.El
.Bd -literal
search inside the given files or directories
for the given keywords,
if you want to show multiple information,
separate them by space like:
--filter err warn ...
.Ed
.Bd -literal
you can forward the result to be processed by a mode
directly with the additional --mode flag
.Ed
.Bd -literal
Note: This option is NOT case sensitive
.Ed
.Bd -literal
if you want to find any kind of termination,
that is not normal, use --extend:
.Ed
.Bd -literal
Examples:
--filter exception gpu -s
--filter error warnings --mode analyse
.Ed
.
.It Fl Fl std-log Ar standard-log
The standard log files usually look something like
.Qq job_452_237.log ,
if for whatever reason the format is not
.Qq .log ,
then you can change it with this argument.
.
.It Fl Fl std-err Ar standard-err
The standard error files usually look something like
.Qq job_452_237.err ,
if for whatever reason the format is not
.Qq .err ,
then you can change it with this argument.
.
.It Fl Fl std-out Ar standard-out
The standard output files usually look something like
.Qq job_452_237.out ,
if for whatever reason the format is not
.Qq .out ,
then you can change it with this argument.
.
.It Fl Fl show-more Ar keywords
show information inside the (if generated) stdout and stderr files,
related to the current log file.
.Bd -literal
Valid arguments are:

[std-err, std-out]

errors and warnings regarding a stderr file (.err)
output to get every line of the stdout file (.out)

if you want to show multiple information,
separate them by space like:
--show std-err std-out
.Ed
.
.It Fl Fl ignore Ar keywords
ignore a given set of information
.Bd -literal
Valid arguments are:

[execution-details, times, errors, host-nodes,
 used-resources, requested-resources,
 allocated-resources, all-resources]

if you want to ignore multiple information,
separate them by space like:
--ignore times errors
.Ed
.
.It Fl r | Fl Fl recursive
Run recursively through given directories
.
.It Fl c | Fl Fl config Ar config
Use args specified by a config file.
Check CONFIG section for more details
.
.It Fl Fl no-config
Do not search for a config file
.
.It Fl Fl reverse-dns-lookup
Resolve the host the job was running on by it's ip address
to a related domain name, if possible.
Else, go with the ip address.
.
.It Fl v | Fl Fl verbose
Start the script in verbose mode, this will generate more detailed output,
about what the script is doing
but printing it to stdout
.
.It Fl Fl generate-log-file
Related to the verbose mode,
this will generate the same output but not onto the terminal.
This will create a log rotation file: htcompact.log or append output to it.
The maximum size is limited by 1 MB,
which means the output starts to rollover on a backup file: htcompact.log.1
.
.It Fl Fl tolerated-usage Ar threshold
Threshold to warn the user,
when a given percentage is
exceeded between used and requested resources
.
.It Fl Fl bad-usage Ar threshold
Threshold to signal overuse/waste of resources,
when a given percentage is exceeded
between used and requested resources
.
.Sh CONFIG
.Bd -literal -compact
Args that start with '--' (eg. -f) can also be set in a config file. Config file
syntax allows: key=value, flag=true, stuff=[a,b,c]
If an arg is specified in more than one place, then
commandline values override config file values which override defaults.

See the config specification:
.Lk https://github.com/psyinfra/htcompact/blob/master/config/README.md

The script is also checking for other config files in other places:
.
"project_dir/config/htcomapct.conf",
 "/etc/htcompact.conf" and "~/.config/htcompact/htcompact.conf"
.Ed
.Bd -literal
with different priorities from 1 (high) to 5 (low):
Priority[1] -c | --config config_file
Priority[2] search for config_file in project_dir/config/htcompact.conf
Priority[3] search for config_file in ~/.config/htcompact/htcompact.conf
Priority[4] search for config_file in /etc/htcompact.conf
Priority[5] run with default settings
.Ed
.
.Sh FEATURES
.Bd -literal -compact
- Always try to generate output, if possible
- Listening to stdin to make the use of tools like grep possible
-> --filter is a more naive alternative to grep
.Ed
.
.Sh FILES
.Bl -tag -width Ds
.It Pa config/htcompact.conf
A default setup for this script.
.El
.
.Sh EXIT STATUS
.Ex -std
.Bd -literal -compact
Exit Codes:
No given files: 1
Wrong options or arguments: 2
TypeError: 3
Keyboard interruption: 4
.Ed
.
.Sh EXAMPLES
.Bd -literal
htcompact -a 398_440.log
htcompact -s log_directory --ignore execution-details --no-config
htcompact -as log_directory
htcompact -e 005
htcompact --filter "" --extend -s --ignore all-resources log_directory
htcompact htcompact.conf 394_440 -a --show-output
htcompact --filter aborted -as ~/logs
OR
grep -R -l aborted ~/logs | htcompact -as
.Ed
.
.Sh SEE ALSO
.Bd -literal
The repository is available at
.Lk https://github.com/psyinfra/htcompact
Bug reports, patches, and (constructive) input are always welcome.
.Ed
.
.Sh AUTHORS
.Nm
was created by
.An Mathis Loevenich
.Mt mathisloevenich@fz\[hy]juelich.de .
See the AUTHORS file for more information.
.
.Sh COPYRIGHT
.Nm
is released under the
.Qq MIT License .
See the LICENSE file for more information.
