.Dd May 26, 2020
.Dt HTCOMPACT 1
.Os \" Current operating system.
.
.Sh NAME
.Nm htcompact
.Nd summarize and analyse HTCondor job log files
.
.Sh SYNOPSIS
.Nm
.Op Ar
.Op Fl hsav
.Op Fl m Ar mode
.Op Fl Fl help
.Op Fl Fl version
.Op Fl Fl verbose
.Op Fl Fl mode Ar mode
.Op Fl Fl std-log Ar suffix
.Op Fl Fl std-out Ar suffix
.Op Fl Fl std-err Ar suffix
.Op Fl Fl ignore Ar keywords
.Op Fl Fl show-more Ar keywords
.Op Fl Fl no-config
.Op Fl Fl to-csv
.Op Fl Fl generate-log-file
.Op Fl Fl filter Ar keywords Op Fl Fl extend
.Op Fl Fl print-event-table
.Op Fl Fl reverse-dns-lookup
.Op Fl Fl table-format Ar tablefmt
.
.Sh DESCRIPTION
The
.Nm
script takes files and directories as input with given flags and prints out a
readable result of found HTCondor log files.
The default and analyser mode can also show a look inside a running process,
however it's not meaningful for summation purposes, so that all summation modes
will only focus on terminated jobs.
.Pp
Its arguments are as follows:
.Bl -tag -width Ds
.
.It Ar FILES
just pass any log files, config files or directories, you just need to separate them by space.
.
.It Ar OPTIONS
.
.It Fl h | Fl Fl help
Prints a summary of
.Nm Ap s
command\[hy]line options and exits.
.
.It Fl Fl print-events-table
Prints a table of known HTCondor events and their descriptions.
.
.It Fl m Ar mode | Fl Fl mode Ar mode
Specify the mode, to interpret HTCondor log files,
.Bd -literal
Valid arguments:
 ['a' or 'analyse', 's' or 'summarize',
 'as' or 'analysed-summary', 'd' or 'default']
.Ed
.Bd -literal
the standard mode of the script is 'default'
.Ed
.
.It Fl s
Short for
.Fl Fl mode Ar summarize .
When used with
.Fl a ,
it's the same as
.Fl Fl mode Ar analysed-summary
.
.It Fl a
Short for
.Fl Fl mode Ar analyse .
When used with
.Fl s ,
it's the same as
.Fl Fl mode Ar analysed-summary
.
.It Fl Fl filter Ar keywords Op OPTIONS
Its options are as follows:
.Bl -tag -width Ds
.It Ar OPTIONS
.Op Fl m Ar mode | Fl Fl mode Ar mode
.Op Fl Fl extend
.
.It Fl m Ar mode | Fl Fl mode Ar mode
Forward the results, to be processed.
Example: analyse the results
.It Fl Fl extend
will include these keywords:
.Bd -literal
["err", "error", "warn", "warning", "exception",
 "aborted", "abortion", "abnormal", "fatal"]
.Ed
.El
.Bd -literal
search inside the given files or directories
for the given keywords,
if you want to give more than one keyword,
use the string notation: "keyword1 keyword2 ...",
or the comma notation:    keyword1,keyword2,...
.Ed
.Bd -literal
you can forward the result to be processed
even without flags after the search process
.Ed
.Bd -literal
Note: This option is NOT case sensitive
.Ed
.Bd -literal
if you want to find any kind of termination,
that is not normal, use --extend:
.Ed
.Bd -literal
Small example:
--filter "exception gpu" -s
--filter error,warnings --mode analyse
.Ed
.
.It Fl Fl std-log Ar standard-log
The standard log files usually look something like
.Qq job_452_237.log ,
if for whatever reason the format is not
.Qq .log ,
then you can change it with this argument.
.
.It Fl Fl std-err Ar standard-err
The standard error files usually look something like
.Qq job_452_237.err ,
if for whatever reason the format is not
.Qq .err ,
then you can change it with this argument.
.
.It Fl Fl std-out Ar standard-out
The standard output files usually look something like
.Qq job_452_237.out ,
if for whatever reason the format is not
.Qq .out ,
then you can change it with this argument.
.
.It Fl Fl show-more Ar keywords
show information inside the (if generated) stdout and stderr files,
related to the current log file.
.Bd -literal
Valid arguments are:

[errors, warnings, output]

errors and warnings regarding a stderr file (.err)
output to get every line of the stdout file (.out)

if you want to show multiple information,
use the string notation: "keyword1 keyword2 ...",
or the comma notation:    keyword1,keyword2,...
.Ed
.
.It Fl Fl ignore Ar keywords
ignore a given set of information
.Bd -literal
Valid arguments are:

[execution-details, times, gpu,
cpu, errors, warnings, host-nodes,
used-resources, requested-resources,
allocated-resources, all-resources]

if you want to ignore multiple information,
use the string notation: "keyword1 keyword2 ...",
or the comma notation:    keyword1,keyword2,...
.Ed
.
.It Fl Fl no-config
Do not search for a config file
.
.It Fl Fl to-csv
Restructure the resource table into a csv format
.
.It Fl Fl reverse-dns-lookup
Resolve the host the job was running on by it's ip address
to a related domain name, if possible.
Else, go with the ip address.
.
.It Fl v | Fl Fl verbose
Start the script in verbose mode, this will generate more detailed output,
about what the script is doing
but printing it to stdout
.
.It Fl Fl generate-log-file
Related to the verbose mode,
this will generate the same output but not onto the terminal.
This will create a log rotation file: htcompact.log or append output to it.
The maximum size is limited by 1 MB,
which means the output starts to rollover on a backup file: htcompact.log.1
.
.It Fl Fl table-format Ar format
the table format for the output
.
valid arguments are:
.
[plain, simple, github, grid, fancy_grid, pipe,
orgtbl, rst, mediawiki, html, latex, latex_raw,
latex_booktabs, tsv, pretty]
.
default: pretty
.El
.
.Sh CONFIG
.Bd -literal -compact
furthermore all these variables|settings can be set inside a config file.
See the config specification:
.Lk https://github.com/psyinfra/htcompact/blob/master/CONFIG.md
.
The script is also checking for other config files in other places:
.
"project_directory/config", "/etc" and "~/.config/htcompact/"
.Ed
.Bd -literal
with different priorities from 1 (high) to 5 (low):
Priority[1] find config_file directly
Priority[2] search for config_file in project_directory/config
Priority[3] search for config_file in ~/.config/htcompact
Priority[4] search for config_file in /etc
Priority[5] run with default settings
.Ed
.
.Sh FEATURES
.Bd -literal -compact
- Always try to generate output, if possible
- Listening to stdin to make the use of tools like grep possible
-> --filter is a more naive alternative to grep
.Ed
.
.Sh FILES
.Bl -tag -width Ds
.It Pa script/htcompact.conf
A default setup for this script.
.El
.
.Sh EXIT STATUS
.Ex -std
.
.Sh EXAMPLES
.Bd -literal
htcompact -a 398_440.log
htcompact -s log_directory --ignore execution-details --no-config
htcompact -as log_directory
htcompact -e 005
htcompact --filter "" --extend -s --ignore all-resources log_directory
htcompact htcompact.conf 394_440 -a --show-output --table-format simple
htcompact --filter "aborted" -as ~/logs
OR
grep -R -l aborted ~/logs | htcompact -as
.Ed
.
.Sh SEE ALSO
.Bd -literal
The repository is available at
.Lk https://github.com/psyinfra/htcompact
Bug reports, patches, and (constructive) input are always welcome.
.Ed
.
.Sh AUTHORS
.Nm
was created by
.An Mathis Loevenich
.Mt mathisloevenich@fz\[hy]juelich.de .
See the AUTHORS file for more information.
.
.Sh COPYRIGHT
.Nm
is released under the
.Qq MIT License .
See the LICENSE file for more information.
